packages:
  - "packages/@netrun/*"
  - "packages/@netrun-cms/*"
  - "packages/client"
  - "packages/cli"
  - "packages/next"
  - "apps/*"
  - "plugins/*"
  - "plugins/@kog/*"
  - "plugins/@intirfix/*"
  - "plugins/@poppies/*"
