/**
 * Stitch Service — wraps Google Stitch design generation API.
 *
 * When STITCH_API_KEY is configured, calls go to the live Stitch API.
 * Otherwise falls back to a mock that returns sample data so the rest of
 * the stack (routes, UI, converter) can be developed and tested.
 */

export type DeviceType = 'DESKTOP' | 'MOBILE' | 'TABLET';

export interface StitchScreen {
  screenId: string;
  projectId: string;
  previewUrl: string;
  code: string;
}

export interface StitchProject {
  projectId: string;
  name: string;
}

// ---------------------------------------------------------------------------
// Sample / mock data used when STITCH_API_KEY is not set
// ---------------------------------------------------------------------------

const SAMPLE_HTML = `
<section style="padding:4rem 2rem;text-align:center;background:linear-gradient(135deg,#0f172a,#1e293b);color:#f8fafc">
  <h1 style="font-size:2.5rem;font-weight:700;margin-bottom:1rem">Welcome to Your Site</h1>
  <p style="font-size:1.125rem;color:#94a3b8;max-width:600px;margin:0 auto 2rem">
    A beautifully crafted landing page generated by AI. Edit any section to make it yours.
  </p>
  <a href="#" style="display:inline-block;padding:0.75rem 2rem;background:#3b82f6;color:#fff;border-radius:0.5rem;text-decoration:none;font-weight:600">
    Get Started
  </a>
</section>
<section style="padding:3rem 2rem;display:grid;grid-template-columns:repeat(3,1fr);gap:2rem;max-width:960px;margin:0 auto">
  <div style="padding:1.5rem;border:1px solid #e2e8f0;border-radius:0.75rem">
    <h3 style="font-weight:600;margin-bottom:0.5rem">Fast</h3>
    <p style="color:#64748b;font-size:0.875rem">Lightning-fast performance out of the box.</p>
  </div>
  <div style="padding:1.5rem;border:1px solid #e2e8f0;border-radius:0.75rem">
    <h3 style="font-weight:600;margin-bottom:0.5rem">Beautiful</h3>
    <p style="color:#64748b;font-size:0.875rem">Stunning designs that look great on every device.</p>
  </div>
  <div style="padding:1.5rem;border:1px solid #e2e8f0;border-radius:0.75rem">
    <h3 style="font-weight:600;margin-bottom:0.5rem">Flexible</h3>
    <p style="color:#64748b;font-size:0.875rem">Customize every detail to match your brand.</p>
  </div>
</section>
`.trim();

let mockScreenCounter = 0;

function mockScreenId(): string {
  mockScreenCounter++;
  return `mock-screen-${Date.now()}-${mockScreenCounter}`;
}

// ---------------------------------------------------------------------------
// StitchService
// ---------------------------------------------------------------------------

export class StitchService {
  private apiKey: string | undefined;
  private baseUrl: string;
  private projectId: string | undefined;

  constructor(opts?: { apiKey?: string; baseUrl?: string; projectId?: string }) {
    this.apiKey = opts?.apiKey ?? process.env.STITCH_API_KEY;
    this.baseUrl = opts?.baseUrl ?? process.env.STITCH_BASE_URL ?? 'https://stitchapi.googleapis.com';
    this.projectId = opts?.projectId ?? process.env.STITCH_PROJECT_ID;
  }

  /** True when a real API key is configured. */
  get isConfigured(): boolean {
    return Boolean(this.apiKey);
  }

  // ── Projects ───────────────────────────────────────────────────────────

  async createProject(name: string): Promise<StitchProject> {
    if (!this.isConfigured) {
      const id = `mock-project-${Date.now()}`;
      return { projectId: id, name };
    }

    const res = await fetch(`${this.baseUrl}/v1/projects`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({ name }),
    });
    const data = await res.json();
    return { projectId: data.projectId ?? data.id, name: data.name ?? name };
  }

  // ── Screen generation ──────────────────────────────────────────────────

  async generateScreen(prompt: string, deviceType: DeviceType = 'DESKTOP'): Promise<StitchScreen> {
    if (!this.isConfigured) {
      const screenId = mockScreenId();
      return {
        screenId,
        projectId: this.projectId ?? 'mock-project',
        previewUrl: '',
        code: SAMPLE_HTML,
      };
    }

    const projectId = await this.ensureProject();
    const res = await fetch(`${this.baseUrl}/v1/projects/${projectId}/screens:generateFromText`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({ prompt, deviceType }),
    });
    const data = await res.json();
    return this.toScreen(data, projectId);
  }

  async editScreen(screenId: string, prompt: string): Promise<StitchScreen> {
    if (!this.isConfigured) {
      return {
        screenId,
        projectId: this.projectId ?? 'mock-project',
        previewUrl: '',
        code: SAMPLE_HTML,
      };
    }

    const projectId = await this.ensureProject();
    const res = await fetch(`${this.baseUrl}/v1/projects/${projectId}/screens:edit`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({ screenIds: [screenId], prompt }),
    });
    const data = await res.json();
    const screens = data.screens ?? [data];
    return this.toScreen(screens[0], projectId);
  }

  async getScreenCode(screenId: string): Promise<string> {
    if (!this.isConfigured) return SAMPLE_HTML;

    const projectId = await this.ensureProject();
    const res = await fetch(`${this.baseUrl}/v1/projects/${projectId}/screens/${screenId}/code`, {
      headers: this.headers(),
    });
    const data = await res.json();
    return data.html ?? data.code ?? '';
  }

  async getScreenImage(screenId: string): Promise<string> {
    if (!this.isConfigured) return '';

    const projectId = await this.ensureProject();
    const res = await fetch(`${this.baseUrl}/v1/projects/${projectId}/screens/${screenId}/image`, {
      headers: this.headers(),
    });
    const data = await res.json();
    return data.imageUrl ?? data.url ?? '';
  }

  async generateVariants(screenId: string, count = 3): Promise<StitchScreen[]> {
    if (!this.isConfigured) {
      return Array.from({ length: count }, () => ({
        screenId: mockScreenId(),
        projectId: this.projectId ?? 'mock-project',
        previewUrl: '',
        code: SAMPLE_HTML,
      }));
    }

    const projectId = await this.ensureProject();
    const res = await fetch(`${this.baseUrl}/v1/projects/${projectId}/screens/${screenId}:generateVariants`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({ count }),
    });
    const data = await res.json();
    const screens = data.variants ?? data.screens ?? [];
    return screens.map((s: Record<string, unknown>) => this.toScreen(s, projectId));
  }

  // ── Internals ──────────────────────────────────────────────────────────

  private headers(): Record<string, string> {
    return {
      'Content-Type': 'application/json',
      ...(this.apiKey ? { Authorization: `Bearer ${this.apiKey}` } : {}),
    };
  }

  private async ensureProject(): Promise<string> {
    if (this.projectId) return this.projectId;
    const project = await this.createProject('sigil-cms-designs');
    this.projectId = project.projectId;
    return this.projectId;
  }

  private toScreen(data: Record<string, unknown>, projectId: string): StitchScreen {
    return {
      screenId: (data.screenId ?? data.id ?? mockScreenId()) as string,
      projectId,
      previewUrl: (data.previewUrl ?? data.imageUrl ?? '') as string,
      code: (data.html ?? data.code ?? '') as string,
    };
  }
}
