#!/usr/bin/env python3
"""
Seed missing content pages for netrunsystems.com Sigil CMS migration.

Site ID: 8e6df504-9844-469f-af73-0d329772bee6

Existing pages (NOT recreated):
  home, products, services, about, contact, events, research, ojai,
  kamera, kode, cad, meridian, kog, optikal

Usage:
  python3 scripts/seed-netrun-pages.py | PGPASSWORD=YUVsfGI3a2Yll4jeIgRUiA psql -h localhost -U postgres -d sigil
"""

import json
import uuid

SITE_ID = "8e6df504-9844-469f-af73-0d329772bee6"

# Existing parent page IDs (from DB query)
PRODUCTS_PAGE_ID = "33f2bb4e-8a29-4a1c-88d1-7ee2bca0c1d2"
SERVICES_PAGE_ID = "161ffd69-2814-4d31-9d0e-d7cbab146069"

# We'll create parent pages for legal and docs groups
LEGAL_PAGE_ID = str(uuid.uuid4())
DOCS_PAGE_ID = str(uuid.uuid4())


def sql_str(s):
    """Escape single quotes for SQL."""
    if s is None:
        return ""
    return s.replace("'", "''")


def emit_page(title, slug, full_path, parent_id, template, sort_order, meta_title, meta_desc):
    """Return (page_id, SQL) for a cms_pages INSERT."""
    page_id = str(uuid.uuid4())
    meta_desc_trunc = meta_desc[:160] if meta_desc else None
    meta_title_trunc = meta_title[:60] if meta_title else title[:60]
    parent_clause = f"'{parent_id}'" if parent_id else "NULL"
    sql = (
        f"INSERT INTO cms_pages (id, site_id, parent_id, title, slug, full_path, status, published_at, language, template, sort_order, meta_title, meta_description) VALUES (\n"
        f"  '{page_id}', '{SITE_ID}', {parent_clause}, '{sql_str(title)}', '{sql_str(slug)}', '{sql_str(full_path)}',\n"
        f"  'published', NOW(), 'en', '{template}', {sort_order},\n"
        f"  '{sql_str(meta_title_trunc)}', '{sql_str(meta_desc_trunc)}'\n"
        f");\n"
    )
    return page_id, sql


def emit_block(page_id, block_type, content, sort_order, settings=None):
    """Return SQL for a cms_content_blocks INSERT."""
    block_id = str(uuid.uuid4())
    content_json = sql_str(json.dumps(content, ensure_ascii=False))
    settings_json = sql_str(json.dumps(settings or {}, ensure_ascii=False))
    return (
        f"INSERT INTO cms_content_blocks (id, page_id, block_type, content, sort_order, is_visible, settings) VALUES (\n"
        f"  '{block_id}', '{page_id}', '{block_type}',\n"
        f"  '{content_json}'::jsonb, {sort_order}, true,\n"
        f"  '{settings_json}'::jsonb\n"
        f");\n"
    )


# ============================================================================
# Standard block helpers
# ============================================================================

def hero_block(page_id, headline, subheadline, bg_image, sort=0, cta_text="Contact Us", cta_link="/contact"):
    return emit_block(page_id, "hero", {
        "headline": headline,
        "subheadline": subheadline,
        "backgroundImage": bg_image,
        "ctaText": cta_text,
        "ctaLink": cta_link,
    }, sort)


def feature_grid_block(page_id, headline, features, sort=1, columns=3):
    return emit_block(page_id, "feature_grid", {
        "headline": headline,
        "columns": columns,
        "features": [{"title": f[0], "description": f[1]} for f in features],
    }, sort)


def text_block(page_id, body, sort=1):
    return emit_block(page_id, "text", {
        "body": body,
    }, sort)


def cta_block(page_id, headline, description, sort=99, button_text="Get Started", button_link="/contact"):
    return emit_block(page_id, "cta", {
        "headline": headline,
        "description": description,
        "buttonText": button_text,
        "buttonLink": button_link,
    }, sort)


def pricing_table_block(page_id, tiers, sort=2):
    return emit_block(page_id, "pricing_table", {"tiers": tiers}, sort)


def faq_block(page_id, items, sort=3):
    return emit_block(page_id, "faq", {
        "items": [{"question": q, "answer": a} for q, a in items],
    }, sort)


# ============================================================================
# Generate all SQL
# ============================================================================

sql_parts = []
sql_parts.append("-- ==========================================================")
sql_parts.append("-- Seed missing pages for netrunsystems.com")
sql_parts.append("-- Generated by seed-netrun-pages.py")
sql_parts.append("-- ==========================================================")
sql_parts.append("BEGIN;\n")

# ---------------------------------------------------------------------------
# Parent pages: legal, docs
# ---------------------------------------------------------------------------
sql_parts.append("-- Parent: legal")
sql_parts.append(
    f"INSERT INTO cms_pages (id, site_id, parent_id, title, slug, full_path, status, published_at, language, template, sort_order, meta_title, meta_description) VALUES (\n"
    f"  '{LEGAL_PAGE_ID}', '{SITE_ID}', NULL, 'Legal', 'legal', '/legal',\n"
    f"  'published', NOW(), 'en', 'default', 80,\n"
    f"  'Legal - Netrun Systems', 'Legal documents, privacy policy, terms of service, and EULA for Netrun Systems.'\n"
    f");\n"
)

sql_parts.append("-- Parent: docs")
sql_parts.append(
    f"INSERT INTO cms_pages (id, site_id, parent_id, title, slug, full_path, status, published_at, language, template, sort_order, meta_title, meta_description) VALUES (\n"
    f"  '{DOCS_PAGE_ID}', '{SITE_ID}', NULL, 'Documentation', 'docs', '/docs',\n"
    f"  'published', NOW(), 'en', 'default', 85,\n"
    f"  'Documentation - Netrun Systems', 'Technical documentation, whitepapers, and reference guides for Netrun Systems products.'\n"
    f");\n"
)

# ---------------------------------------------------------------------------
# 1. Blog
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Netrun Blog", "blog", "/blog", None, "blog", 70,
    "Blog - Netrun Systems",
    "Latest news, technical insights, and product updates from Netrun Systems."
)
sql_parts.append("-- Page: blog")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Netrun Blog",
    "Technical insights, product updates, and industry analysis from the Netrun Systems team.",
    "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1920&q=80&fit=crop"))
sql_parts.append(text_block(page_id,
    "## Coming Soon\n\nOur blog is being migrated to the new Sigil CMS platform. Check back soon for technical articles, product announcements, and industry insights.\n\nIn the meantime, feel free to reach out with any questions.", 1))
sql_parts.append(cta_block(page_id, "Have a Question?",
    "Reach out to our team for technical discussions, partnership opportunities, or product inquiries.",
    99, "Contact Us", "/contact"))

# ---------------------------------------------------------------------------
# 2. products/intirkon — Flagship product
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Intirkon", "intirkon", "/products/intirkon", PRODUCTS_PAGE_ID, "landing", 1,
    "Intirkon - Multi-Tenant MSP Management Platform",
    "Intirkon is a multi-tenant MSP management platform with Azure Lighthouse, security feeds, and Client Shield."
)
sql_parts.append("\n-- Page: products/intirkon")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Intirkon",
    "Multi-tenant MSP management platform. Azure Lighthouse integration, unified security feeds, compliance dashboards, and Client Shield tenant isolation.",
    "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1920&q=80&fit=crop",
    0, "Request a Demo", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Platform Capabilities", [
    ("Azure Lighthouse Integration", "Manage multiple customer tenants from a single pane of glass with native Azure Lighthouse delegation and cross-tenant visibility."),
    ("Tenant Isolation", "Row-level security and per-tenant encryption ensure complete data isolation. Each customer environment is logically and cryptographically separated."),
    ("Unified Security Feeds", "Aggregate security alerts from Microsoft Sentinel, Defender for Cloud, and third-party SIEM tools into a single prioritized feed per tenant."),
    ("Compliance Dashboard", "Real-time compliance posture across SOC2, ISO 27001, NIST, and CIS benchmarks with automated evidence collection and gap analysis."),
    ("Client Shield", "Automated threat response and tenant protection. Client Shield detects anomalous activity and applies containment policies before escalation."),
    ("Automated Patching", "Scheduled patching workflows with rollback support. Define maintenance windows per tenant and track patch compliance across your portfolio."),
], 1))
sql_parts.append(pricing_table_block(page_id, [
    {
        "name": "Starter",
        "price": "$499",
        "period": "/month",
        "features": ["Up to 10 tenants", "Azure Lighthouse integration", "Security feed aggregation", "Email support", "Basic compliance reports"],
        "ctaText": "Get Started",
        "ctaLink": "/contact",
        "isPopular": False,
    },
    {
        "name": "Professional",
        "price": "$999",
        "period": "/month",
        "features": ["Up to 50 tenants", "Everything in Starter", "Client Shield protection", "Compliance dashboard", "Automated patching", "Priority support"],
        "ctaText": "Get Started",
        "ctaLink": "/contact",
        "isPopular": True,
    },
    {
        "name": "Enterprise",
        "price": "Custom",
        "period": "",
        "features": ["Unlimited tenants", "Everything in Professional", "Dedicated account manager", "Custom integrations", "SLA guarantee", "On-premises option"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": False,
    },
], 2))
sql_parts.append(faq_block(page_id, [
    ("What is Azure Lighthouse?", "Azure Lighthouse enables cross-tenant management at scale. Intirkon leverages Lighthouse to give MSPs delegated access to customer Azure subscriptions without separate logins or tenant switching."),
    ("How does Client Shield work?", "Client Shield monitors each tenant for anomalous behavior patterns. When threats are detected, it applies automated containment policies and alerts your SOC team within seconds."),
    ("Can I migrate from ConnectWise or Datto?", "Yes. Intirkon includes migration tools for importing customer data, device inventories, and alert configurations from legacy RMM/PSA platforms."),
    ("Is Intirkon SOC2 compliant?", "Intirkon is built with SOC2 Type II controls. The compliance dashboard also helps you maintain your own SOC2 certification with automated evidence collection."),
], 3))
sql_parts.append(cta_block(page_id, "Ready to Modernize Your MSP Stack?",
    "Intirkon replaces fragmented RMM/PSA tools with a unified Azure-native platform. Schedule a demo to see multi-tenant management done right.",
    99, "Schedule a Demo", "/contact"))

# ---------------------------------------------------------------------------
# 3. products/intirkast
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Intirkast", "intirkast", "/products/intirkast", PRODUCTS_PAGE_ID, "landing", 2,
    "Intirkast - AI Content Syndication Platform",
    "Multi-tenant AI content syndication and video generation platform for creators and SMBs."
)
sql_parts.append("\n-- Page: products/intirkast")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Intirkast",
    "Multi-tenant AI content syndication and video generation. Transform blog posts into platform-optimized social media content and AI-generated videos.",
    "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "What Intirkast Does", [
    ("Content Syndication", "Transform long-form blog content into platform-optimized posts for LinkedIn, Twitter, Instagram, and Facebook with AI-powered adaptation."),
    ("AI Video Generation", "Temporal.io-orchestrated pipeline turns written content into narrated video with AI voiceover, motion graphics, and platform-specific formatting."),
    ("Multi-Tenant Architecture", "Each creator or business gets an isolated tenant with their own content library, brand settings, and publishing schedule."),
], 1))
sql_parts.append(cta_block(page_id, "Amplify Your Content",
    "Stop manually reformatting content for every platform. Intirkast automates syndication with AI-powered optimization.",
    99, "Get Started", "/contact"))

# ---------------------------------------------------------------------------
# 4. products/intirfix
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Intirfix", "intirfix", "/products/intirfix", PRODUCTS_PAGE_ID, "landing", 3,
    "Intirfix - IT Service Management",
    "Intirfix is an IT service management platform for tracking incidents, changes, and service requests."
)
sql_parts.append("\n-- Page: products/intirfix")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Intirfix",
    "IT service management built for modern infrastructure teams. Track incidents, manage changes, and streamline service requests.",
    "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "ITSM Capabilities", [
    ("Incident Management", "Track, triage, and resolve incidents with priority-based routing, SLA timers, and automated escalation workflows."),
    ("Change Management", "Structured change request workflows with approval gates, risk assessment, and rollback documentation."),
    ("Service Request Catalog", "Self-service portal where end users can submit requests from a curated catalog with automated fulfillment."),
    ("Configuration Management", "CMDB integration tracks assets, dependencies, and configuration items across your infrastructure."),
], 1))
sql_parts.append(cta_block(page_id, "Streamline Your IT Operations",
    "Replace spreadsheets and email chains with structured ITSM workflows. Intirfix brings order to IT operations.",
    99, "Get Started", "/contact"))

# ---------------------------------------------------------------------------
# 5. products/netrun-kare
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "KARE", "netrun-kare", "/products/netrun-kare", PRODUCTS_PAGE_ID, "landing", 4,
    "KARE - Managed Intirkon Service",
    "KARE is a managed service where Netrun Systems operates your Intirkon tenant on your behalf."
)
sql_parts.append("\n-- Page: products/netrun-kare")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "KARE",
    "Managed Intirkon service. Netrun Systems operates your Intirkon tenant on your behalf so you can focus on your business, not your infrastructure.",
    "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "What You Get", [
    ("Fully Managed Tenant", "Netrun provisions, configures, and maintains your Intirkon environment. We handle patching, monitoring, and security so you don''t have to."),
    ("24/7 Monitoring", "Our operations team monitors your tenant around the clock. Incidents are detected and addressed before they impact your customers."),
    ("Compliance as a Service", "We maintain compliance posture across SOC2, ISO 27001, and NIST frameworks with regular audits and evidence collection."),
    ("Dedicated Account Manager", "A named Netrun engineer serves as your primary point of contact for escalations, change requests, and strategic planning."),
], 1))
sql_parts.append(pricing_table_block(page_id, [
    {
        "name": "KARE Standard",
        "price": "$1,499",
        "period": "/month",
        "features": ["Managed Intirkon tenant", "Up to 25 endpoints", "8x5 monitoring", "Monthly reports", "Email support"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": False,
    },
    {
        "name": "KARE Professional",
        "price": "$2,999",
        "period": "/month",
        "features": ["Everything in Standard", "Up to 100 endpoints", "24/7 monitoring", "Client Shield active", "Dedicated account manager", "Weekly reports"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": True,
    },
    {
        "name": "KARE Enterprise",
        "price": "Custom",
        "period": "",
        "features": ["Unlimited endpoints", "Everything in Professional", "Custom SLA", "On-site support available", "Quarterly business reviews"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": False,
    },
], 2))
sql_parts.append(cta_block(page_id, "Let Us Run Your Infrastructure",
    "KARE takes the operational burden off your team. We manage Intirkon so you can focus on growing your business.",
    99, "Contact Sales", "/contact"))

# ---------------------------------------------------------------------------
# 6. products/netrun-klip
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "KLIP", "netrun-klip", "/products/netrun-klip", PRODUCTS_PAGE_ID, "landing", 5,
    "KLIP - Snapshot Reporting",
    "KLIP delivers concise snapshot reports for infrastructure health, compliance, and performance metrics."
)
sql_parts.append("\n-- Page: products/netrun-klip")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "KLIP",
    "Snapshot reporting for infrastructure health, compliance posture, and performance metrics. Get the signal without the noise.",
    "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Reporting Features", [
    ("Infrastructure Snapshots", "Point-in-time capture of your infrastructure state including resource utilization, availability, and configuration drift."),
    ("Compliance Summaries", "One-page compliance snapshots showing posture against SOC2, ISO 27001, and NIST benchmarks with trend indicators."),
    ("Executive Dashboards", "Clean, printable reports designed for non-technical stakeholders. Metrics that matter without the operational noise."),
], 1))
sql_parts.append(cta_block(page_id, "Clear Reporting, Zero Noise",
    "KLIP gives you and your stakeholders the visibility you need without the dashboard fatigue.",
    99, "Get Started", "/contact"))

# ---------------------------------------------------------------------------
# 7. products/charlotte
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Charlotte", "charlotte", "/products/charlotte", PRODUCTS_PAGE_ID, "landing", 6,
    "Charlotte - AI Orchestration Platform",
    "Charlotte is an AI orchestrator routing tasks across Claude, GPT, Gemini, and Ollama for optimal cost and performance."
)
sql_parts.append("\n-- Page: products/charlotte")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Charlotte",
    "AI orchestration control plane. Charlotte routes tasks across multiple AI services to optimize cost, capability, and latency.",
    "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Orchestration Capabilities", [
    ("Multi-Model Routing", "Dynamically routes tasks to Claude, GPT-4, Gemini, Ollama, and Azure OpenAI based on task complexity, cost constraints, and latency requirements."),
    ("Voice Interface", "7-mode progressive enhancement architecture supporting voice-driven interaction with real-time streaming responses."),
    ("LLM Cost Optimization", "Automatically selects the most cost-effective model for each task. Use premium models only when the task demands it."),
    ("RAG Integration", "Built-in retrieval-augmented generation with pgvector embeddings for grounding AI responses in your organizational knowledge."),
    ("Agent Orchestration", "Coordinate multi-agent workflows where specialist AI agents collaborate on complex tasks with human-in-the-loop oversight."),
    ("Scale to Zero", "GCP Cloud Run deployment with scale-to-zero. No idle costs when the platform is not processing requests."),
], 1))
sql_parts.append(cta_block(page_id, "Smarter AI, Lower Costs",
    "Charlotte makes multi-model AI practical for production workloads. Route tasks intelligently instead of overpaying for a single provider.",
    99, "Learn More", "/contact"))

# ---------------------------------------------------------------------------
# 8. products/survai
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Survai", "survai", "/products/survai", PRODUCTS_PAGE_ID, "landing", 7,
    "Survai - 3D Scan Pipeline for MEP Planning",
    "Survai is a 3D scan pipeline using LiDAR and YOLOv8 for point cloud processing and MEP planning."
)
sql_parts.append("\n-- Page: products/survai")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Survai",
    "3D scan pipeline for MEP planning. LiDAR capture to YOLOv8 object detection to point cloud processing, all in one workflow.",
    "https://images.unsplash.com/photo-1581092160607-ee67df30e7c0?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Pipeline Stages", [
    ("LiDAR Capture", "Ingest point cloud data from LiDAR scanners and photogrammetry sources. Support for LAZ, LAS, E57, and PLY formats."),
    ("YOLOv8 Object Detection", "AI-powered detection of MEP components (pipes, ducts, conduits, fixtures) in 3D point clouds with bounding box and segmentation output."),
    ("Point Cloud Processing", "PointNet++ segmentation, SAM-based refinement, and automated cleanup for construction-grade accuracy."),
    ("MEP Planning Output", "Generate MEP coordination drawings, clash detection reports, and BIM-ready models from processed scan data."),
], 1))
sql_parts.append(cta_block(page_id, "From Scan to Plan",
    "Survai automates the tedious work between site scanning and MEP coordination. Faster turnaround, fewer errors.",
    99, "Get Started", "/contact"))

# ---------------------------------------------------------------------------
# 9. products/ghostgrid
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "GhostGrid", "ghostgrid", "/products/ghostgrid", PRODUCTS_PAGE_ID, "landing", 8,
    "GhostGrid - Optical Network Infrastructure",
    "GhostGrid is an optical network infrastructure platform for fiber network automation and management."
)
sql_parts.append("\n-- Page: products/ghostgrid")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "GhostGrid",
    "Optical network infrastructure platform. Design, provision, and manage fiber networks with automation-first tooling.",
    "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(text_block(page_id,
    "## Optical Network Automation\n\n"
    "GhostGrid provides tooling for optical network infrastructure management. From fiber route planning to wavelength provisioning, "
    "GhostGrid automates the operational complexity of running optical networks at scale.\n\n"
    "### Key Capabilities\n\n"
    "- **Fiber Route Planning** - Design and optimize fiber paths with geographic and cost constraints\n"
    "- **Wavelength Management** - Automated DWDM wavelength assignment and capacity planning\n"
    "- **Network Monitoring** - Real-time optical power monitoring and fault detection\n"
    "- **Provisioning Automation** - API-driven provisioning workflows for optical circuits\n", 1))
sql_parts.append(cta_block(page_id, "Automate Your Optical Network",
    "GhostGrid brings infrastructure-as-code principles to optical networking.",
    99, "Contact Us", "/contact"))

# ---------------------------------------------------------------------------
# 10. products/patlas
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "PATLAS", "patlas", "/products/patlas", PRODUCTS_PAGE_ID, "landing", 9,
    "PATLAS - Patent Portfolio Management",
    "PATLAS is a patent portfolio management platform for tracking patents, figures, and IP strategy."
)
sql_parts.append("\n-- Page: products/patlas")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "PATLAS",
    "Patent portfolio management. Track patents, manage figure specifications, conduct prior art research, and organize your IP strategy.",
    "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "IP Management Features", [
    ("Patent Tracking", "Centralized registry for your patent portfolio with status tracking, deadline alerts, and filing history."),
    ("Figure Specifications", "FIGR rendering engine generates patent-quality SVG diagrams from structured figure definitions."),
    ("Prior Art Research", "KAMERA-powered prior art search and competitive intelligence to strengthen your patent applications."),
    ("Portfolio Analytics", "Visualize your IP landscape with technology coverage maps, citation networks, and competitive positioning."),
], 1))
sql_parts.append(cta_block(page_id, "Organize Your IP Portfolio",
    "PATLAS brings structure to patent management. From filing to maintenance, keep your intellectual property organized and actionable.",
    99, "Get Started", "/contact"))

# ---------------------------------------------------------------------------
# 11. products/meshbook
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Meshbook", "meshbook", "/products/meshbook", PRODUCTS_PAGE_ID, "landing", 10,
    "Meshbook - Documentation Platform",
    "Meshbook is a documentation platform for creating and publishing technical docs and knowledge bases."
)
sql_parts.append("\n-- Page: products/meshbook")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Meshbook",
    "Documentation platform for technical teams. Create, organize, and publish knowledge bases, API docs, and runbooks.",
    "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Documentation Features", [
    ("Structured Knowledge Base", "Organize documentation in hierarchical collections with full-text search, version history, and cross-references."),
    ("API Documentation", "Auto-generate API reference docs from OpenAPI specs with interactive examples and code snippets."),
    ("Collaborative Editing", "Real-time collaborative editing with review workflows, comments, and change tracking."),
    ("Multi-Format Publishing", "Publish to web, PDF, and Markdown. Single source of truth with multiple output formats."),
], 1))
sql_parts.append(cta_block(page_id, "Documentation That Scales",
    "Meshbook keeps your team aligned with a single source of truth for all technical documentation.",
    99, "Get Started", "/contact"))

# ---------------------------------------------------------------------------
# 12. products/eiscore
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "EISCORE", "eiscore", "/products/eiscore", PRODUCTS_PAGE_ID, "landing", 11,
    "EISCORE 5.6 - UE5 Action RPG",
    "EISCORE 5.6 is an Unreal Engine 5.6 action RPG with NPC civilization simulation and Mass AI."
)
sql_parts.append("\n-- Page: products/eiscore")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "EISCORE 5.6",
    "Unreal Engine 5.6 action RPG with NPC civilization simulation. Mass AI, procedural content generation, and emergent gameplay.",
    "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Game Features", [
    ("NPC Civilization Simulation", "Autonomous NPC factions that build settlements, trade resources, wage wars, and evolve culture using Mass AI behavioral systems."),
    ("Mass AI Architecture", "Thousands of concurrent AI agents with StateTree-driven behavior, each making independent decisions based on needs, relationships, and world state."),
    ("Procedural Content Generation", "PCG-driven world building creates unique landscapes, dungeons, and points of interest that respond to player and NPC activity."),
    ("Motion Matching Combat", "Fluid animation-driven combat system using UE5.6 Motion Matching for responsive, context-aware character movement."),
], 1))
sql_parts.append(cta_block(page_id, "A Living World",
    "EISCORE combines simulation depth with action RPG gameplay. Every playthrough tells a different story.",
    99, "Follow Development", "/contact"))

# ---------------------------------------------------------------------------
# 13. products/dungeonmaster
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "INTIRQUEST", "dungeonmaster", "/products/dungeonmaster", PRODUCTS_PAGE_ID, "landing", 12,
    "INTIRQUEST - Fantasy Sports Trading Platform",
    "INTIRQUEST is a multi-asset fantasy market gaming platform combining stock trading and fantasy sports."
)
sql_parts.append("\n-- Page: products/dungeonmaster")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "INTIRQUEST",
    "Multi-asset fantasy market gaming platform. Stock trading meets fantasy sports in unified competitive leagues.",
    "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1920&q=80&fit=crop",
    0, "Learn More", "/contact"))
sql_parts.append(feature_grid_block(page_id, "Platform Features", [
    ("Fantasy Market Leagues", "Create and join leagues where players build portfolios combining real stock picks with fantasy sports assets."),
    ("Real-Time Trading", "Live market data integration with Socket.IO-powered real-time portfolio updates and competitive leaderboards."),
    ("GraphQL Federation", "Apollo Federation v2 gateway connects auth, leagues, portfolios, and ML subgraphs into a unified API."),
    ("Mobile App", "React Native mobile app with Expo for iOS and Android. Trade, track, and compete on the go."),
], 1))
sql_parts.append(cta_block(page_id, "Where Finance Meets Fantasy",
    "INTIRQUEST gamifies market knowledge. Build portfolios, compete in leagues, and sharpen your trading instincts.",
    99, "Learn More", "/contact"))

# ---------------------------------------------------------------------------
# 14. services/cloud-audit
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Cloud Audit", "cloud-audit", "/services/cloud-audit", SERVICES_PAGE_ID, "landing", 1,
    "Cloud Audit - Infrastructure Assessment",
    "Comprehensive cloud infrastructure audit covering security, cost optimization, and compliance posture."
)
sql_parts.append("\n-- Page: services/cloud-audit")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Cloud Audit",
    "Comprehensive infrastructure assessment. We evaluate your cloud environment for security gaps, cost waste, and compliance risk.",
    "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&q=80&fit=crop",
    0, "Schedule an Audit", "/contact"))
sql_parts.append(text_block(page_id,
    "## What We Assess\n\n"
    "Our cloud audit covers every layer of your infrastructure:\n\n"
    "- **Security Posture** - IAM policies, network segmentation, encryption at rest and in transit, secrets management\n"
    "- **Cost Optimization** - Right-sizing, reserved instance coverage, orphaned resources, storage tiering\n"
    "- **Compliance** - SOC2, ISO 27001, NIST, and CIS benchmark alignment with gap analysis\n"
    "- **Architecture Review** - High availability, disaster recovery, scalability patterns, and technical debt\n"
    "- **Operational Maturity** - CI/CD pipelines, monitoring coverage, incident response, and runbook completeness\n\n"
    "You receive a detailed report with prioritized findings, remediation steps, and an estimated timeline for each recommendation.\n", 1))
sql_parts.append(pricing_table_block(page_id, [
    {
        "name": "Quick Assessment",
        "price": "$2,500",
        "period": "one-time",
        "features": ["Single cloud account", "Security + cost review", "Written report", "1-hour review call"],
        "ctaText": "Book Now",
        "ctaLink": "/contact",
        "isPopular": False,
    },
    {
        "name": "Full Audit",
        "price": "$7,500",
        "period": "one-time",
        "features": ["Multi-account environment", "Security, cost, compliance", "Architecture review", "Detailed remediation plan", "2-hour review + Q&A"],
        "ctaText": "Book Now",
        "ctaLink": "/contact",
        "isPopular": True,
    },
    {
        "name": "Ongoing Advisory",
        "price": "$2,500",
        "period": "/month",
        "features": ["Everything in Full Audit", "Monthly re-assessment", "Slack channel access", "Remediation support", "Quarterly business review"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": False,
    },
], 2))
sql_parts.append(cta_block(page_id, "Know Where You Stand",
    "A cloud audit gives you a clear picture of your infrastructure health. No surprises, no guesswork.",
    99, "Schedule Your Audit", "/contact"))

# ---------------------------------------------------------------------------
# 15. services/ai-assessment
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "AI Readiness Assessment", "ai-assessment", "/services/ai-assessment", SERVICES_PAGE_ID, "landing", 2,
    "AI Readiness Assessment",
    "Evaluate your organization readiness for AI adoption with a structured assessment of data, infrastructure, and use cases."
)
sql_parts.append("\n-- Page: services/ai-assessment")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "AI Readiness Assessment",
    "Evaluate where AI fits in your organization. We assess your data, infrastructure, and workflows to identify high-impact AI opportunities.",
    "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1920&q=80&fit=crop",
    0, "Get Assessed", "/contact"))
sql_parts.append(text_block(page_id,
    "## What We Evaluate\n\n"
    "Our AI readiness assessment covers five dimensions:\n\n"
    "- **Data Maturity** - Quality, accessibility, and governance of your data assets\n"
    "- **Infrastructure Readiness** - Compute, storage, and networking capacity for AI workloads\n"
    "- **Use Case Identification** - High-impact opportunities where AI delivers measurable ROI\n"
    "- **Team Capability** - Skills assessment and training recommendations for your engineering team\n"
    "- **Risk & Compliance** - Data privacy, bias mitigation, and regulatory considerations\n\n"
    "The output is a prioritized roadmap with quick wins, medium-term projects, and strategic initiatives.\n", 1))
sql_parts.append(pricing_table_block(page_id, [
    {
        "name": "Assessment",
        "price": "$5,000",
        "period": "one-time",
        "features": ["5-dimension evaluation", "Use case prioritization", "Written roadmap", "Executive presentation", "1-hour review call"],
        "ctaText": "Book Now",
        "ctaLink": "/contact",
        "isPopular": True,
    },
    {
        "name": "Assessment + POC",
        "price": "$15,000",
        "period": "one-time",
        "features": ["Everything in Assessment", "Proof-of-concept build", "Top use case implemented", "Performance benchmarks", "Go/no-go recommendation"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": False,
    },
], 2))
sql_parts.append(cta_block(page_id, "AI Without the Hype",
    "We help you separate real AI opportunities from vendor noise. Practical assessment, actionable roadmap.",
    99, "Schedule Assessment", "/contact"))

# ---------------------------------------------------------------------------
# 16. services/agentic-coding
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Agentic Coding", "agentic-coding", "/services/agentic-coding", SERVICES_PAGE_ID, "landing", 3,
    "Agentic Coding - AI-Accelerated Development",
    "Agentic development services using AI coding agents for 3-14x faster delivery on software projects."
)
sql_parts.append("\n-- Page: services/agentic-coding")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Agentic Coding",
    "AI-accelerated software development. Our agentic development practice delivers production software 3-14x faster than traditional approaches.",
    "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1920&q=80&fit=crop",
    0, "Start a Project", "/contact"))
sql_parts.append(text_block(page_id,
    "## What Is Agentic Development?\n\n"
    "Agentic coding uses AI coding agents orchestrated by experienced engineers to build production software at dramatically accelerated timelines. "
    "This is not code generation pasted from ChatGPT. It is a structured SDLC practice with human oversight at every stage.\n\n"
    "### Proven Velocity Multipliers\n\n"
    "| Project Complexity | Speed Improvement |\n"
    "|---|---|\n"
    "| Simple (landing pages, CRUD apps) | 10-14x faster |\n"
    "| Medium (multi-service APIs, dashboards) | 6.5-8.5x faster |\n"
    "| Complex (multi-tenant platforms, ML pipelines) | 3.3-5x faster |\n"
    "| Enterprise (compliance-heavy, regulated) | 2.5-4x faster |\n\n"
    "### How It Works\n\n"
    "1. **Scope & Architecture** - We define the system architecture and break work into agent-friendly tasks\n"
    "2. **Agent Orchestration** - Specialist AI agents handle implementation under engineer supervision\n"
    "3. **Quality Gates** - Every output passes code review, testing, and security checks\n"
    "4. **Delivery** - Production-ready code with documentation, tests, and deployment pipelines\n", 1))
sql_parts.append(cta_block(page_id, "Build Faster, Ship Sooner",
    "Agentic development is how Netrun Systems builds its own products. Now it is available as a service.",
    99, "Start Your Project", "/contact"))

# ---------------------------------------------------------------------------
# 17. services/virtual-tours
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Virtual Tours", "virtual-tours", "/services/virtual-tours", SERVICES_PAGE_ID, "landing", 4,
    "Virtual Tours - 3D Scanning Services",
    "Professional 3D scanning and virtual tour creation for real estate, construction, and commercial properties."
)
sql_parts.append("\n-- Page: services/virtual-tours")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "Virtual Tours",
    "Professional 3D scanning and virtual tour creation. LiDAR-powered captures for real estate, construction, and commercial properties.",
    "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1920&q=80&fit=crop",
    0, "Book a Scan", "/contact"))
sql_parts.append(text_block(page_id,
    "## 3D Scanning Services\n\n"
    "We capture physical spaces with LiDAR scanners and deliver immersive virtual tours, floor plans, and point cloud data.\n\n"
    "### Use Cases\n\n"
    "- **Real Estate** - Virtual property tours for listings, remote viewing, and marketing\n"
    "- **Construction** - Progress documentation, as-built verification, and MEP coordination\n"
    "- **Commercial** - Facility documentation, space planning, and insurance records\n"
    "- **Heritage** - Historical preservation scanning and digital archival\n", 1))
sql_parts.append(pricing_table_block(page_id, [
    {
        "name": "Standard Scan",
        "price": "$500",
        "period": "per property",
        "features": ["Up to 2,000 sq ft", "Virtual tour delivery", "Floor plan generation", "48-hour turnaround"],
        "ctaText": "Book Now",
        "ctaLink": "/contact",
        "isPopular": False,
    },
    {
        "name": "Professional",
        "price": "$1,200",
        "period": "per property",
        "features": ["Up to 10,000 sq ft", "Virtual tour + point cloud", "Floor plans + measurements", "Schematic floor plan", "24-hour turnaround"],
        "ctaText": "Book Now",
        "ctaLink": "/contact",
        "isPopular": True,
    },
    {
        "name": "Enterprise",
        "price": "Custom",
        "period": "",
        "features": ["Unlimited sq ft", "Full point cloud data", "BIM-ready output", "MEP coordination", "Dedicated project manager"],
        "ctaText": "Contact Sales",
        "ctaLink": "/contact",
        "isPopular": False,
    },
], 2))
sql_parts.append(cta_block(page_id, "Capture Any Space",
    "Professional 3D scanning with fast turnaround. Real estate, construction, or commercial - we scan it all.",
    99, "Book a Scan", "/contact"))

# ---------------------------------------------------------------------------
# 18. legal/privacy-policy
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Privacy Policy", "privacy-policy", "/legal/privacy-policy", LEGAL_PAGE_ID, "default", 1,
    "Privacy Policy - Netrun Systems",
    "Privacy policy for Netrun Systems products and services."
)
sql_parts.append("\n-- Page: legal/privacy-policy")
sql_parts.append(sql)
sql_parts.append(text_block(page_id,
    "## Privacy Policy\n\n"
    "**Effective Date:** March 28, 2026\n\n"
    "**Netrun Systems, Inc.** (\"Company\", \"we\", \"us\") operates netrunsystems.com and associated SaaS products. "
    "This Privacy Policy explains how we collect, use, disclose, and safeguard your information.\n\n"
    "### 1. Information We Collect\n\n"
    "**Information you provide:** Name, email address, company name, and payment information when you create an account, "
    "purchase a service, or contact us.\n\n"
    "**Automatically collected:** IP address, browser type, operating system, referring URLs, pages visited, "
    "and timestamps via server logs and analytics.\n\n"
    "**Cookies:** We use essential cookies for authentication and session management. Analytics cookies are used "
    "only with your consent.\n\n"
    "### 2. How We Use Your Information\n\n"
    "- Provide, maintain, and improve our services\n"
    "- Process transactions and send related information\n"
    "- Send administrative notifications (service updates, security alerts)\n"
    "- Respond to your comments, questions, and support requests\n"
    "- Monitor and analyze trends, usage, and activity\n\n"
    "### 3. Information Sharing\n\n"
    "We do not sell your personal information. We may share information with:\n\n"
    "- **Service providers** who assist in operating our platform (hosting, payment processing, analytics)\n"
    "- **Legal obligations** when required by law, regulation, or legal process\n"
    "- **Business transfers** in connection with a merger, acquisition, or sale of assets\n\n"
    "### 4. Data Security\n\n"
    "We implement industry-standard security measures including encryption at rest and in transit, "
    "access controls, and regular security assessments. No method of transmission over the Internet is 100% secure.\n\n"
    "### 5. Data Retention\n\n"
    "We retain personal information for as long as your account is active or as needed to provide services. "
    "You may request deletion of your data by contacting us at privacy@netrunsystems.com.\n\n"
    "### 6. Your Rights\n\n"
    "Depending on your jurisdiction, you may have the right to access, correct, delete, or port your personal data. "
    "California residents have additional rights under the CCPA.\n\n"
    "### 7. Changes to This Policy\n\n"
    "We may update this policy from time to time. We will notify you of material changes via email or a notice on our website.\n\n"
    "### 8. Contact\n\n"
    "For privacy-related inquiries: privacy@netrunsystems.com\n\n"
    "Netrun Systems, Inc.\n"
    "Ojai, California\n", 0))

# ---------------------------------------------------------------------------
# 19. legal/terms-of-service
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Terms of Service", "terms-of-service", "/legal/terms-of-service", LEGAL_PAGE_ID, "default", 2,
    "Terms of Service - Netrun Systems",
    "Terms of service governing the use of Netrun Systems products and website."
)
sql_parts.append("\n-- Page: legal/terms-of-service")
sql_parts.append(sql)
sql_parts.append(text_block(page_id,
    "## Terms of Service\n\n"
    "**Effective Date:** March 28, 2026\n\n"
    "These Terms of Service (\"Terms\") govern your use of the websites, products, and services provided by "
    "**Netrun Systems, Inc.** (\"Company\", \"we\", \"us\").\n\n"
    "### 1. Acceptance of Terms\n\n"
    "By accessing or using our services, you agree to be bound by these Terms. If you do not agree, do not use our services.\n\n"
    "### 2. Services\n\n"
    "Netrun Systems provides cloud infrastructure management platforms, AI tools, consulting services, and related SaaS products. "
    "Service availability, features, and pricing may change with notice.\n\n"
    "### 3. Accounts\n\n"
    "You are responsible for maintaining the security of your account credentials. You must notify us immediately of any "
    "unauthorized access. You are responsible for all activity under your account.\n\n"
    "### 4. Acceptable Use\n\n"
    "You agree not to:\n"
    "- Use our services for unlawful purposes\n"
    "- Attempt to gain unauthorized access to our systems\n"
    "- Interfere with or disrupt service availability\n"
    "- Reverse engineer, decompile, or disassemble our software\n"
    "- Resell access without written authorization\n\n"
    "### 5. Intellectual Property\n\n"
    "All content, software, and intellectual property in our services remain the property of Netrun Systems. "
    "Your subscription grants a limited, non-exclusive license to use the service.\n\n"
    "### 6. Payment Terms\n\n"
    "Paid services are billed in advance on a monthly or annual basis. Refunds are handled per our refund policy. "
    "We reserve the right to change pricing with 30 days notice.\n\n"
    "### 7. Limitation of Liability\n\n"
    "To the maximum extent permitted by law, Netrun Systems shall not be liable for indirect, incidental, special, "
    "consequential, or punitive damages arising from your use of our services.\n\n"
    "### 8. Indemnification\n\n"
    "You agree to indemnify Netrun Systems against claims arising from your use of our services or violation of these Terms.\n\n"
    "### 9. Termination\n\n"
    "We may suspend or terminate your access for violation of these Terms. You may cancel your account at any time.\n\n"
    "### 10. Governing Law\n\n"
    "These Terms are governed by the laws of the State of California, without regard to conflict of law principles.\n\n"
    "### 11. Contact\n\n"
    "Questions about these Terms: legal@netrunsystems.com\n\n"
    "Netrun Systems, Inc.\n"
    "Ojai, California\n", 0))

# ---------------------------------------------------------------------------
# 20. legal/eula
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "End User License Agreement", "eula", "/legal/eula", LEGAL_PAGE_ID, "default", 3,
    "EULA - Netrun Systems",
    "End user license agreement for Netrun Systems software products."
)
sql_parts.append("\n-- Page: legal/eula")
sql_parts.append(sql)
sql_parts.append(text_block(page_id,
    "## End User License Agreement (EULA)\n\n"
    "**Effective Date:** March 28, 2026\n\n"
    "This End User License Agreement (\"Agreement\") is between you and **Netrun Systems, Inc.** (\"Licensor\") "
    "for the use of our software products.\n\n"
    "### 1. License Grant\n\n"
    "Subject to payment of applicable fees, Licensor grants you a non-exclusive, non-transferable, revocable license "
    "to use the software in accordance with the applicable subscription plan.\n\n"
    "### 2. Restrictions\n\n"
    "You may not:\n"
    "- Copy, modify, or distribute the software except as expressly permitted\n"
    "- Reverse engineer, decompile, or disassemble the software\n"
    "- Sublicense, rent, or lease the software to third parties\n"
    "- Remove or alter any proprietary notices or labels\n"
    "- Use the software to build a competing product\n\n"
    "### 3. Ownership\n\n"
    "The software and all intellectual property rights remain the exclusive property of Netrun Systems. "
    "This Agreement does not transfer any ownership rights.\n\n"
    "### 4. Data\n\n"
    "You retain ownership of your data. We process your data solely to provide the service as described in our Privacy Policy.\n\n"
    "### 5. Support and Updates\n\n"
    "Support and software updates are provided according to your subscription plan. We may release updates at our discretion.\n\n"
    "### 6. Warranty Disclaimer\n\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO "
    "THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.\n\n"
    "### 7. Limitation of Liability\n\n"
    "IN NO EVENT SHALL NETRUN SYSTEMS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES "
    "ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT.\n\n"
    "### 8. Termination\n\n"
    "This Agreement terminates when your subscription ends or if you violate any term. Upon termination, "
    "you must cease all use of the software. Data export is available for 30 days after termination.\n\n"
    "### 9. Governing Law\n\n"
    "This Agreement is governed by the laws of the State of California.\n\n"
    "### 10. Contact\n\n"
    "Questions: legal@netrunsystems.com\n\n"
    "Netrun Systems, Inc.\n"
    "Ojai, California\n", 0))

# ---------------------------------------------------------------------------
# 21. ojai-it
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "IT Services for Ojai Valley", "ojai-it", "/ojai-it", None, "landing", 75,
    "IT Services for Ojai Valley",
    "Professional IT services for homes and businesses in the Ojai Valley. Local, reliable, expert support."
)
sql_parts.append("\n-- Page: ojai-it")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "IT Services for Ojai Valley",
    "Local IT support for homes and businesses in the Ojai Valley. Network setup, device support, cloud migration, and cybersecurity from a neighbor you can trust.",
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80&fit=crop",
    0, "Get Help", "/contact"))
sql_parts.append(feature_grid_block(page_id, "What We Offer", [
    ("Home Network Setup", "Wi-Fi optimization, mesh network installation, smart home integration, and network security for residential properties."),
    ("Business IT Support", "Managed IT services for small businesses including workstation setup, backup, email migration, and help desk support."),
    ("Cloud Migration", "Move your business to Microsoft 365, Google Workspace, or cloud-hosted applications with guided migration and training."),
    ("Cybersecurity", "Endpoint protection, phishing awareness training, password management, and security audits for small businesses."),
    ("Device Support", "Mac, Windows, and mobile device troubleshooting, setup, and maintenance. On-site visits available."),
    ("Data Recovery", "Hard drive recovery, backup configuration, and disaster recovery planning for homes and businesses."),
], 1))
sql_parts.append(pricing_table_block(page_id, [
    {
        "name": "On-Call",
        "price": "$125",
        "period": "/hour",
        "features": ["On-site or remote support", "No commitment", "Same-day response", "Residential + business"],
        "ctaText": "Book a Visit",
        "ctaLink": "/contact",
        "isPopular": False,
    },
    {
        "name": "Monthly Retainer",
        "price": "$299",
        "period": "/month",
        "features": ["4 hours included", "Priority scheduling", "Remote monitoring", "Email + phone support", "Discounted on-site rate"],
        "ctaText": "Get Started",
        "ctaLink": "/contact",
        "isPopular": True,
    },
    {
        "name": "Business Managed",
        "price": "$799",
        "period": "/month",
        "features": ["Unlimited remote support", "8 on-site hours included", "Endpoint monitoring", "Backup management", "Quarterly security review"],
        "ctaText": "Contact Us",
        "ctaLink": "/contact",
        "isPopular": False,
    },
], 2))
sql_parts.append(cta_block(page_id, "Local IT Support You Can Trust",
    "Based in Ojai, serving the entire valley. No call centers, no ticket queues. Just responsive, expert IT support from your neighbor.",
    99, "Contact Us", "/contact"))

# ---------------------------------------------------------------------------
# 22. kare (redirect alias to products/netrun-kare)
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "KARE", "kare", "/kare", None, "landing", 76,
    "KARE - Managed Intirkon Service",
    "KARE is a managed service where Netrun Systems operates your Intirkon tenant on your behalf."
)
sql_parts.append("\n-- Page: kare (alias to products/netrun-kare)")
sql_parts.append(sql)
sql_parts.append(hero_block(page_id, "KARE",
    "Managed Intirkon service. Netrun Systems operates your Intirkon tenant so you can focus on your business.",
    "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1920&q=80&fit=crop",
    0, "Learn More", "/products/netrun-kare"))
sql_parts.append(cta_block(page_id, "See Full KARE Details",
    "Visit the full KARE product page for features, pricing, and service tiers.",
    1, "View KARE Product Page", "/products/netrun-kare"))

# ---------------------------------------------------------------------------
# 23. docs/intirkon-whitepaper
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "Intirkon Platform Whitepaper", "intirkon-whitepaper", "/docs/intirkon-whitepaper", DOCS_PAGE_ID, "default", 1,
    "Intirkon Whitepaper - Netrun Systems",
    "Executive summary of the Intirkon multi-tenant MSP management platform architecture and capabilities."
)
sql_parts.append("\n-- Page: docs/intirkon-whitepaper")
sql_parts.append(sql)
sql_parts.append(text_block(page_id,
    "## Intirkon Platform Whitepaper\n\n"
    "### Executive Summary\n\n"
    "Intirkon is a multi-tenant managed service provider (MSP) management platform built on Microsoft Azure. "
    "It replaces fragmented RMM, PSA, and security tools with a unified platform that leverages Azure Lighthouse "
    "for cross-tenant management at scale.\n\n"
    "### The Problem\n\n"
    "MSPs today operate with a patchwork of disconnected tools: one for remote monitoring, another for ticketing, "
    "another for security, and yet another for compliance. Each tool has its own tenant model, its own dashboards, "
    "and its own billing. The result is operational complexity that scales linearly with customer count.\n\n"
    "### The Solution\n\n"
    "Intirkon consolidates MSP operations into a single platform:\n\n"
    "- **Azure Lighthouse** provides delegated access to customer subscriptions without credential sharing\n"
    "- **Unified security feeds** aggregate alerts from Sentinel, Defender for Cloud, and third-party sources\n"
    "- **Client Shield** applies automated threat containment per tenant based on configurable policy rules\n"
    "- **Compliance dashboard** tracks posture against SOC2, ISO 27001, NIST, and CIS benchmarks\n"
    "- **Row-level security** ensures complete data isolation between tenants at the database layer\n\n"
    "### Architecture\n\n"
    "Intirkon uses a FastAPI backend with SQLAlchemy and PostgreSQL (with RLS), a React 18 frontend with TypeScript, "
    "and Azure infrastructure including Key Vault, Service Bus, and Container Apps. The platform is designed for "
    "horizontal scaling with tenant-aware routing at every layer.\n\n"
    "### Target Market\n\n"
    "Intirkon is built for MSPs managing 10-500 customer environments who want to consolidate tooling, "
    "reduce per-tenant operational cost, and differentiate with security-first managed services.\n\n"
    "For a full demo or technical deep-dive, contact us at sales@netrunsystems.com.\n", 0))

# ---------------------------------------------------------------------------
# 24. docs/ghostgrid-whitepaper
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "GhostGrid Whitepaper", "ghostgrid-whitepaper", "/docs/ghostgrid-whitepaper", DOCS_PAGE_ID, "default", 2,
    "GhostGrid Whitepaper - Netrun Systems",
    "Executive summary of the GhostGrid optical network infrastructure platform."
)
sql_parts.append("\n-- Page: docs/ghostgrid-whitepaper")
sql_parts.append(sql)
sql_parts.append(text_block(page_id,
    "## GhostGrid Optical Network Whitepaper\n\n"
    "### Executive Summary\n\n"
    "GhostGrid is an optical network infrastructure platform for automating the design, provisioning, "
    "and management of fiber optic networks. It brings infrastructure-as-code principles to the physical network layer.\n\n"
    "### The Challenge\n\n"
    "Optical network operations remain largely manual. Fiber route planning uses spreadsheets and GIS tools "
    "that do not integrate. Wavelength assignment is done by hand. Capacity planning is reactive rather than predictive. "
    "The result is slow provisioning, underutilized capacity, and costly truck rolls.\n\n"
    "### GhostGrid Approach\n\n"
    "GhostGrid provides:\n\n"
    "- **Fiber Route Optimization** - Algorithmic route planning considering geographic constraints, "
    "right-of-way costs, and redundancy requirements\n"
    "- **DWDM Wavelength Management** - Automated wavelength assignment with conflict detection and capacity forecasting\n"
    "- **Network Monitoring** - Real-time optical power monitoring, fault localization, and performance trending\n"
    "- **Provisioning Automation** - API-driven circuit provisioning workflows that reduce turn-up time from weeks to hours\n"
    "- **Inventory Tracking** - Fiber strand management, splice point documentation, and cable plant records\n\n"
    "### Technology\n\n"
    "GhostGrid is built with Python for network automation logic, integrating with equipment vendor APIs "
    "and standard network management protocols. The platform supports both greenfield deployments and brownfield "
    "integration with existing fiber plant.\n\n"
    "For technical inquiries, contact engineering@netrunsystems.com.\n", 0))

# ---------------------------------------------------------------------------
# 25. docs/kamera-whitepaper
# ---------------------------------------------------------------------------
page_id, sql = emit_page(
    "KAMERA OSINT Whitepaper", "kamera-whitepaper", "/docs/kamera-whitepaper", DOCS_PAGE_ID, "default", 3,
    "KAMERA Whitepaper - Netrun Systems",
    "Executive summary of KAMERA, an OSINT research and intelligence tool for due diligence and analysis."
)
sql_parts.append("\n-- Page: docs/kamera-whitepaper")
sql_parts.append(sql)
sql_parts.append(text_block(page_id,
    "## KAMERA OSINT Intelligence Whitepaper\n\n"
    "### Executive Summary\n\n"
    "KAMERA is an open-source intelligence (OSINT) research and intelligence tool. It performs company and individual "
    "analysis, risk scoring, narrative report generation, and due diligence research using AI-powered analysis pipelines.\n\n"
    "### The Problem\n\n"
    "Due diligence and OSINT research is time-intensive. Analysts manually search public records, corporate filings, "
    "social media, news archives, and domain registrations. Synthesizing findings into a coherent narrative requires "
    "hours of expert labor per subject.\n\n"
    "### How KAMERA Works\n\n"
    "KAMERA automates the OSINT research workflow:\n\n"
    "- **Data Collection** - Automated gathering from public records, corporate registries, news sources, "
    "social media profiles, and domain/IP records\n"
    "- **AI Narrative Analysis** - Gemini-powered analysis synthesizes collected data into structured intelligence narratives "
    "with context, connections, and risk indicators\n"
    "- **Risk Scoring** - Algorithmic risk assessment based on financial indicators, litigation history, "
    "regulatory actions, and reputation signals\n"
    "- **Report Generation** - Structured PDF reports with executive summary, detailed findings, risk assessment, "
    "and recommended actions\n"
    "- **Batch Processing** - Process multiple subjects in parallel on cloud infrastructure with scale-to-zero economics\n\n"
    "### Use Cases\n\n"
    "- **Investor Due Diligence** - Research potential investments, partners, or acquisition targets\n"
    "- **Vendor Risk Assessment** - Evaluate third-party vendors for security and compliance risk\n"
    "- **Competitive Intelligence** - Monitor competitors, market entrants, and industry trends\n"
    "- **Background Research** - Pre-meeting research on prospects, advisors, or collaborators\n\n"
    "### Infrastructure\n\n"
    "KAMERA runs on GCP Cloud Run with scale-to-zero, using PostgreSQL for metadata and Cloud Storage for reports. "
    "Processing costs are incurred only when scans are running.\n\n"
    "For inquiries about KAMERA research services, contact research@netrunsystems.com.\n", 0))

# ---------------------------------------------------------------------------
# Close transaction
# ---------------------------------------------------------------------------
sql_parts.append("\nCOMMIT;\n")
sql_parts.append(f"\n-- Verification: count pages for site")
sql_parts.append(f"SELECT COUNT(*) AS total_pages FROM cms_pages WHERE site_id = '{SITE_ID}';")
sql_parts.append(f"SELECT COUNT(*) AS total_blocks FROM cms_content_blocks cb JOIN cms_pages p ON cb.page_id = p.id WHERE p.site_id = '{SITE_ID}';")

# Print all SQL
print("\n".join(sql_parts))
