/**
 * Marketplace Plugin — Database Schema (raw SQL for runMigration)
 *
 * Tables:
 * - cms_installed_plugins: tracks third-party plugins installed per tenant
 * - cms_plugin_registry: curated directory of available plugins
 */

export const MIGRATION_SQL = `
  CREATE TABLE IF NOT EXISTS cms_installed_plugins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES cms_tenants(id) ON DELETE CASCADE,
    plugin_id VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    version VARCHAR(50) NOT NULL,
    source VARCHAR(20) DEFAULT 'npm',
    source_url TEXT,
    is_enabled BOOLEAN DEFAULT true,
    config JSONB DEFAULT '{}',
    installed_by VARCHAR(255),
    installed_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(tenant_id, plugin_id)
  );

  CREATE INDEX IF NOT EXISTS idx_cms_installed_plugins_tenant
    ON cms_installed_plugins(tenant_id);

  CREATE TABLE IF NOT EXISTS cms_plugin_registry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plugin_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    author VARCHAR(255),
    version VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    icon_name VARCHAR(50),
    downloads INTEGER DEFAULT 0,
    rating INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT false,
    is_verified BOOLEAN DEFAULT false,
    source_type VARCHAR(20) DEFAULT 'npm',
    source_url TEXT,
    readme TEXT,
    required_env JSONB DEFAULT '[]',
    tags JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_cms_plugin_registry_category
    ON cms_plugin_registry(category);
  CREATE INDEX IF NOT EXISTS idx_cms_plugin_registry_featured
    ON cms_plugin_registry(is_featured);
`;

/**
 * Built-in Sigil plugins to seed into the registry.
 * Uses ON CONFLICT DO NOTHING for idempotent seeding.
 */
export const BUILT_IN_PLUGINS = [
  {
    pluginId: 'seo',
    name: 'SEO (Sitemap + RSS)',
    description: 'Automatic sitemap.xml and RSS feed generation for all sites.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'content',
    iconName: 'Rss',
    isFeatured: true,
    isVerified: true,
    requiredEnv: [],
    tags: ['seo', 'sitemap', 'rss', 'feed'],
  },
  {
    pluginId: 'artist',
    name: 'Artist Content',
    description: 'Music releases, events, and artist profile management for musician sites.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'content',
    iconName: 'Disc3',
    isFeatured: true,
    isVerified: true,
    requiredEnv: [],
    tags: ['music', 'artist', 'releases', 'events'],
  },
  {
    pluginId: 'mailing-list',
    name: 'Mailing List',
    description: 'Email subscriber collection and management with embeddable signup forms.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'content',
    iconName: 'Mail',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['email', 'newsletter', 'subscribers'],
  },
  {
    pluginId: 'contact',
    name: 'Contact & Booking',
    description: 'Contact form submissions and booking inquiry management.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'content',
    iconName: 'Inbox',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['contact', 'form', 'booking', 'inquiry'],
  },
  {
    pluginId: 'photos',
    name: 'Photo Manager',
    description: 'Upload, organize, and serve photos with multi-cloud storage support (GCS, Azure, S3).',
    author: 'Netrun Systems',
    version: '2.0.0',
    category: 'content',
    iconName: 'Camera',
    isFeatured: true,
    isVerified: true,
    requiredEnv: [],
    tags: ['photos', 'images', 'media', 'gallery'],
  },
  {
    pluginId: 'advisor',
    name: 'AI Advisor',
    description: 'AI-powered design and content advisor using Gemini.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'utility',
    iconName: 'Bot',
    isFeatured: true,
    isVerified: true,
    requiredEnv: ['GEMINI_API_KEY'],
    tags: ['ai', 'advisor', 'gemini', 'design'],
  },
  {
    pluginId: 'store',
    name: 'Store (Stripe)',
    description: 'Full e-commerce with Stripe: product catalog, checkout sessions, and order tracking.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'commerce',
    iconName: 'ShoppingBag',
    isFeatured: true,
    isVerified: true,
    requiredEnv: ['STRIPE_SECRET_KEY'],
    tags: ['store', 'stripe', 'ecommerce', 'payments', 'checkout'],
  },
  {
    pluginId: 'printful',
    name: 'Merch (Printful)',
    description: 'Print-on-demand merchandise via Printful integration.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'commerce',
    iconName: 'Shirt',
    isFeatured: false,
    isVerified: true,
    requiredEnv: ['PRINTFUL_API_KEY'],
    tags: ['merch', 'printful', 'print-on-demand'],
  },
  {
    pluginId: 'paypal',
    name: 'PayPal Payments',
    description: 'Accept payments via PayPal checkout integration.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'commerce',
    iconName: 'CreditCard',
    isFeatured: false,
    isVerified: true,
    requiredEnv: ['PAYPAL_CLIENT_ID', 'PAYPAL_CLIENT_SECRET'],
    tags: ['paypal', 'payments', 'checkout'],
  },
  {
    pluginId: 'booking',
    name: 'Appointment Booking',
    description: 'Service catalog, availability management, and appointment scheduling.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'commerce',
    iconName: 'CalendarCheck',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['booking', 'appointments', 'scheduling', 'calendar'],
  },
  {
    pluginId: 'docs',
    name: 'Documentation & Knowledge Base',
    description: 'Articles, categories, search, and user feedback for documentation portals.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'content',
    iconName: 'FileText',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['docs', 'documentation', 'knowledge-base', 'articles'],
  },
  {
    pluginId: 'resonance',
    name: 'Resonance Analytics',
    description: 'A/B testing, experiments, and content performance analytics.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'analytics',
    iconName: 'Activity',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['analytics', 'ab-testing', 'experiments', 'metrics'],
  },
  {
    pluginId: 'migrate',
    name: 'Site Migration',
    description: 'Import content from WordPress, Ghost, and other CMS platforms.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'utility',
    iconName: 'Upload',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['migration', 'import', 'wordpress', 'ghost'],
  },
  {
    pluginId: 'webhooks',
    name: 'Webhooks & Events',
    description: 'Configure webhook endpoints to receive CMS events (page published, order completed, etc.).',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'integration',
    iconName: 'Webhook',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['webhooks', 'events', 'automation', 'integration'],
  },
  {
    pluginId: 'kamera',
    name: 'KAMERA (3D Scanning)',
    description: 'Integration with Survai 3D scanning pipeline for spatial content.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'integration',
    iconName: 'ScanLine',
    isFeatured: false,
    isVerified: true,
    requiredEnv: ['SURVAI_API_URL'],
    tags: ['3d', 'scanning', 'survai', 'spatial'],
  },
  {
    pluginId: 'kog',
    name: 'KOG CRM',
    description: 'CRM integration with KOG for customer and deal management.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'integration',
    iconName: 'UserPlus',
    isFeatured: false,
    isVerified: true,
    requiredEnv: ['KOG_API_URL'],
    tags: ['crm', 'kog', 'customers', 'deals'],
  },
  {
    pluginId: 'intirkast',
    name: 'Intirkast Broadcasting',
    description: 'Live broadcasting and streaming integration with Intirkast platform.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'integration',
    iconName: 'Radio',
    isFeatured: false,
    isVerified: true,
    requiredEnv: ['INTIRKAST_API_URL'],
    tags: ['broadcasting', 'streaming', 'live', 'intirkast'],
  },
  {
    pluginId: 'charlotte',
    name: 'Charlotte AI Assistant',
    description: 'AI-powered assistant integration with Charlotte for automated support.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'utility',
    iconName: 'Bot',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['ai', 'assistant', 'charlotte', 'chatbot'],
  },
  {
    pluginId: 'support',
    name: 'Support Panel',
    description: 'Customer support ticket management and help desk.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'utility',
    iconName: 'HelpCircle',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['support', 'tickets', 'help-desk'],
  },
  {
    pluginId: 'community',
    name: 'Community Forum',
    description: 'Discussion forums and community management for your sites.',
    author: 'Netrun Systems',
    version: '1.0.0',
    category: 'content',
    iconName: 'Users',
    isFeatured: false,
    isVerified: true,
    requiredEnv: [],
    tags: ['forum', 'community', 'discussions'],
  },
];
